NewsPortal/NEWS/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import (PostView, PostCategoryView, CommentView, ArticleView, SearchView, 
                    PostUpdate, PostDelete, PostCreate, subscriptions, CategoryListView, subscribe,)
from django.views.decorators.cache import cache_page


urlpatterns = [
    # path — означает путь.
    # В данном случае путь ко всем товарам у нас останется пустым,
    # чуть позже станет ясно почему.
    # Т.к. наше объявленное представление является классом,
    # а Django ожидает функцию, нам надо представить этот класс в виде view.
    # Для этого вызываем метод as_view.
    path('', cache_page(60)(PostView.as_view()), name='post_list'),
    # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
    # int — указывает на то, что принимаются только целочисленные значения
    path('<int:pk>',cache_page(300)(PostCategoryView.as_view())),
    path('comment/<int:pk>', CommentView.as_view()),
    path('article/<int:pk>', ArticleView.as_view()),
    path('search/', SearchView.as_view()),
    path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/', PostView.as_view(), name='post_detail'),
    path('categories/<int:pk>/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe/', subscribe, name='subscribe'),
    path('subscriptions/', subscriptions, name='subscriptions'),
   
]

NewsPortal/projecttest/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from NEWS import views

router = routers.DefaultRouter()
router.register(r'/article', views.ArticleViewset)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
    path('news/', include('NEWS.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),


]

NewsPortal/NEWS/models.py
from django.db import models

from django.core.validators import MinValueValidator

from django.contrib.auth.models import User

from django.db.models import Sum

from django.urls import reverse

from django.core.cache import cache

from django.utils.translation import pgettext_lazy

from django.utils.translation import gettext as _


# Товар для нашей витрины
class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,  # названия товаров не должны повторяться
    )
    description = models.TextField()
    quantity = models.IntegerField(
        validators=[MinValueValidator(0)],
    )
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',  # все продукты в категории будут доступны через поле products
       verbose_name=pgettext_lazy('help text for MyModel model', 'This is the help text'),
    )
    price = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )

    def __str__(self):
        return f'{self.name.title()}: {self.description[:10]}'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])


# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    name = models.CharField(max_length=100, unique=True, help_text=_('category name'))
    subscribers = models.ManyToManyField(User, blank=True, related_name='categories')
    
    def __str__(self):
        return self.name.title()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAutor = pRat * 3 + cRat
        self.save()


# class Category(models.Model):
#     name = models.CharField(max_length=64, unique=True)


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dataCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

        
     def get_absolute_url(self):
         return reverse('post_detail', args=[str(self.id)])
     
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post_detail-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его



class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPortal/templates/article.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}


<!-- Название у нас будет Product -->
{% block title %}
    Article
{% endblock title %}


<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}


   <h1>новость</h1>
   <hr>
   <hr>
   {% if article %}
       <table>
           <tr>
              <td>Автор</td>
                <td>Дата публикации</td>
                <td>Категория новости</td>
                <td>Тема</td>
                {#Условие получается составным. #}
                {% if perms.NEWS.change_post or perms.NEWS.delete_post %}
                <td>Основной текст</td>
                <td>Рейтинг</td>
           </tr>

           {% for article in articles %}
           <tr>
              <td>{{ article.author }}</td>
                <td>{{ article.dataCreation}}</td>
                <td>{{ article.title}}</td>
                <td>{{ article.categoryType }}</td>
                <td>{{ article.text|truncatewords:2 |censor }}</td>
                <td>{{ article.rating }}</td>
           </tr>

            {% endfor %}
       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
        {% endif %}




{{ post_detail }}
{% endblock content %}

NewsPortal/templates/category.html
  <!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет products -->
{% block title %}
Category
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все статьи</h1>
{{ category }}
{% endblock content %}

NewsPortal/templates/category_list.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}


<!-- Название у нас будет Product -->
{% block title %}
    Posts
{% endblock title %}


<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
    <h1>Все новости</h1>
    <h3>{{ time_now|date:'M d Y' }}</h3>
    {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
    <form action="" method="get">
    {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
    {{ filterset.form.as_p }}
    {# Добавим кнопку отправки данных формы #}
    <input type="submit" value="найти"/>
</form>

<hr>

{# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
{% if perms.news.add_post %}
<a href="{% url 'post_create' %}">Добавить новость</a>
{% endif %}

{% if posts %}
<table>
    <tr>
        <td>Автор</td>
        <td>Дата публикации</td>
        <td>Категория новости</td>
        <td>Тема</td>
          {#Условие получается составным. #}
         {% if perms.NEWS.change_post or perms.NEWS.delete_post %}
         <td>Основной текст</td>
         <td>Рейтинг</td>
        {% endif %}
    </tr>

    <!-- Для каждого товара будете генерироваться новая строчка,
    т.е. новый HTML код, который указан в теле цикла.
    При этом сам цикл работает точно так же, как и в Python.
    product — переменная цикла, т.е. наш товар полученный из списка -->
    {% for post in posts %}
    <tr>
        <td>{{ post.author }}</td>
        <td>{{ post.dataCreation}}</td>
        <td>{{ post.title}}</td>
        <td>{{ post.categoryType }}</td>
        <td>{{ post.text|truncatewords:2 |censor }}</td>
        <td>{{ post.rating }}</td>
           </tr>

        <td>
            {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
            {% if perms.NEWS.change_post %}
            <a href="{% url 'post_update' pk=post.id %}">Изменить</a>
            {% endif %}
            {% if perms.news.delete_post %}
            <a href="{% url 'post_delete' post.id %}">Удалить</a>
            {% endif %}
        </td>

    </tr>
    {% endfor %}

</table>
{% else %}
<h2>Новостей нет!</h2>
{% endif %}

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?page=1">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}


{{ post_detail }}
{% endblock content %}

NewsPortal/templates/comment.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}


<!-- Название у нас будет Product -->
{% block title %}
Comment
{% endblock title %}




<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ comment.text }}</h1>
{% endblock content %}

NewsPortal/templates/cost_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новая <a href="{{ link }}">статья</a> в вашем любимом разделе!</h2>
        <p>{{ text }}</p>
</body>
</html>

NewsPortal/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
  <h2>Здравствуйте! Новые статьи за неделю!</h2>
     <ul>
      {% for post in posts %}
        <li><a href="{{ link }}{{ post.get_absolute_url}}">{{ post.title }}</a></li>
     {% endfor %}
     </ul>
</body>
</html>

NewsPortal/templates/post.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Product -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ post }}</h1>
{% endblock content %}

NewsPortal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPortal/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/posts.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}


<!-- Название у нас будет Product -->
{% block title %}
    Posts
{% endblock title %}


<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
    <h1>Все новости</h1>
    <h3>{{ time_now|date:'M d Y' }}</h3>
    {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
    <form action="" method="get">
    {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
    {{ filterset.form.as_p }}
    {# Добавим кнопку отправки данных формы #}
    <input type="submit" value="найти"/>
</form>

<hr>

{# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
{% if perms.news.add_post %}
<a href="{% url 'post_create' %}">Добавить новость</a>
{% endif %}

{% if posts %}
<table>
    <tr>
        <td>Автор</td>
        <td>Дата публикации</td>
        <td>Категория новости</td>
        <td>Тема</td>
          {#Условие получается составным. #}
         {% if perms.NEWS.change_post or perms.NEWS.delete_post %}
         <td>Основной текст</td>
         <td>Рейтинг</td>
        {% endif %}
    </tr>

    <!-- Для каждого товара будете генерироваться новая строчка,
    т.е. новый HTML код, который указан в теле цикла.
    При этом сам цикл работает точно так же, как и в Python.
    product — переменная цикла, т.е. наш товар полученный из списка -->
    {% for post in posts %}
    <tr>
        <td>{{ post.author }}</td>
        <td>{{ post.dataCreation}}</td>
        <td>{{ post.title}}</td>
        <td>{{ post.categoryType }}</td>
        <td>{{ post.text|truncatewords:2 |censor }}</td>
        <td>{{ post.rating }}</td>
           </tr>

        <td>
            {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
            {% if perms.NEWS.change_post %}
            <a href="{% url 'post_update' pk=post.id %}">Изменить</a>
            {% endif %}
            {% if perms.news.delete_post %}
            <a href="{% url 'post_delete' post.id %}">Удалить</a>
            {% endif %}
        </td>

    </tr>
    {% endfor %}

</table>
{% else %}
<h2>Новостей нет!</h2>
{% endif %}

{# Добавляем пагинацию на страницу #}

{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %}
<a href="?page=1">1</a>
{% if page_obj.previous_page_number != 1 %}
...
<a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
{% if paginator.num_pages != page_obj.next_page_number %}
...
<a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
{% endif %}
{% endif %}


{{ post_detail }}
{% endblock content %}

NewsPortal/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPortal/templates/search.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_tags %}


<!-- Название у нас будет Product -->
{% block title %}
    Search
{% endblock title %}


<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}


   <h1>Все новости</h1>
    <form action="" method="get" >
        {{ filterset.form.non_field_errors }}

        {{ filterset.form.title__icontains.errors }}
        <label for="{{ filterset.form.title__icontains.id_for_label }}">Search</label>
        <input
            id="{{ filterset.form.title__icontains.id_for_label }}"
            name="{{ filterset.form.title__icontains.name }}"
            value="{{ filterset.form.title__icontains.value }}"
            class="form-control"
        >
        <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>

   <hr>
   {% if searches %}
       <table>
           <tr>
                <td>Автор</td>
                <td>Дата публикации</td>
                <td>Категория новости</td>
                <td>Тема</td>
                {#Условие получается составным. #}
                {% if perms.NEWS.change_post or perms.NEWS.delete_post %}
                <td>Основной текст</td>
                <td>Рейтинг</td>
           </tr>

           <!-- Для каждого товара будете генерироваться новая строчка,
           т.е. новый HTML код, который указан в теле цикла.
           При этом сам цикл работает точно так же, как и в Python.
           product — переменная цикла, т.е. наш товар полученный из списка -->
           {% for search in searches %}
           <tr>
                <td>{{ search.author }}</td>
                <td>{{ search.dataCreation}}</td>
                <td>{{ search.title}}</td>
                <td>{{ search.categoryType }}</td>
                <td>{{ search.text|truncatewords:2 |censor }}</td>
                <td>{{ search.rating }}</td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
      {% endif %}





{{ post_detail }}
{% endblock content %}

NewsPortal/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <h1 class="text-center">{{ message }}ff category f</h1>
{% endblock content %}

NewsPortal/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                 {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}